development:
  adapter: postgresql
  encoding: utf8
  database: sage-wanted_development
  pool: 5
  username: ianwessen
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: sage-wanted_test
  pool: 5
  username: ianwessen
  password:

cucumber:
  <<: *TEST