# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18ca67b64d52248776f319e6702e356f7f677ee5fa78d736493a306105d346d1f892119a9c46f9712ea0474f8bbdda38881eabda97b4993ed1be7026450d51fb

test:
  secret_key_base: 362865ff169ee48c6c67a1bfb6b56876af177b929a42e1cea78bb7923abfd5b752a9802468e2133d52405921716aa953f1abda78dd843ab75751915a2bad7ec4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
